version: '3'

services:
  react:
    container_name: react
    build: .
    volumes:
      - ./src/app/src
      - ./pubilc/assets:/app/public/assets
      - ./app/node.modules
    ports:
    - 3000:3000
    stdin_open: true
    command: npm start
